### ISSUE TITLE
eventsource: keys are never deleted from globalDecoderMap.

### ISSUE THREAD

**Issue by alevinval** [alevinval/sse#18]
When a new decoder is spawned, a global map is updated with the `EventSource <-> Decoder` pair in  `globalDecoderMap`.

The pair is registered when a connect succeeds. But never deleted.

When the closing logic runs, it should perform the cleanup from `globalDecoderMap.`
To do that, the decoder should become a member of `EventSource` and be created right after the connect succeeds, instead of creating it under `consume()`

**Comment by dolmen** [comment]
The `globalDecoderMap` is just an awful hack.

`retry` should just be parsed into `Event` by `decoder.Decode`: add a `Retry` member to `Event` (which by the way should be a concrete type, not an interface).

**Comment by alevinval** [comment]
Hi @dolmen,

I agree that it feels like a hack.

The way I was understanding the spec influenced me to think that `Decoder` should somehow be doing direct manipulation of the EventSource.

> ... interpret the field value as an integer in base ten, **and set the event stream's reconnection time to that integer**.

I think the problem is that there is both:
- events for the user/consumer of the stream.
- control events for the eventsource implementation.

I got stuck into thinking that `Decoder` should be returning only "user-grade" events.

 Should there be two `Event` structs? A low level one, which adds a retry field. Then a high level one that reaches the user, created by the eventsource. Then, `Decoder` would return low level events (data+control) and `EventSource` only data events.

I will sleep on that a bit more.

**Comment by alevinval** [comment]
Oh well, check this:
- https://github.com/mubit/sse/pull/24

Decoder returns `RawEvent`, and EventSource lets the event reach the user if its not a control one.

Interfaces!
