### ISSUE TITLE
proposal: provide an encoder implementation.

### ISSUE THREAD

**Issue by alevinval** [alevinval/sse#20]
Originally, the goal of the library was to implement a compliant consumer of SSE HTTP streams.

As the project matures, we could afford to be _batteries included_ if we also provided a compliant producer of SSE HTTP streams.

The proposal is to provide an `Encoder` implementation.

**Comment by dolmen** [comment]
You usually do not both sides in the same program. I don't see a valid reason to have both server and client side in the same package (and net/http is not a good example for me: having both client and server in the same package confuses me).

**Comment by alevinval** [comment]
I do agree with that. I'll close the proposal.

**Comment by dolmen** [comment]
One risk in providing both server and client in the same package it to be tempted to use the server to test the client (and vice versa) and to have bugs on one side hidden by mirror bugs on the other side: that would not validate interoperability.
