### ISSUE TITLE
eventsource_test: server not closed?

### ISSUE THREAD

**Issue by dolmen** [alevinval/sse#26]
I'm not yet familiar with the `net/http/httptest` package, but in its documentation I see for [`NewServer`](https://golang.org/pkg/net/http/httptest/#NewServer):
```
The caller should call Close when finished, to shut it down.
```
But I don't see any calls to `s.Close()` in `eventsource_test.go`.

Note: I tried to add myself some `defer s.Close()` after every `s, config := newServer()` calls, but that doesn't work. I really have to learn `net/http/httptest` and to understand `eventsource_test.go`...

**Comment by alevinval** [comment]
Apparently, it would look as if the EventSource is not closing the http connection.

```
go test -v -run=TestNewEventSourceWithInvalidContentType ./...
=== RUN   TestNewEventSourceWithInvalidContentType
2016/11/02 19:41:34 httptest.Server blocked in Close after 5 seconds, waiting for connections:
  *net.TCPConn 0xc42002c078 127.0.0.1:62943 in state active
```

**Comment by alevinval** [comment]
This is happening on the following tests:
- TestNewEventSourceWithInvalidContentType
- TestEventSourceLastEventID
- TestEventSourceRetryIsRespected
- TestDropConnectionCanReconnect

**Comment by alevinval** [comment]
Oh ... the spam is strong. I will avoid referencing issues on commits, at least while I'm still refining it.
