### ISSUE TITLE
Expose ReadyState changes using a channel

### ISSUE THREAD

**Issue by dolmen** [alevinval/sse#37]
Like MessageEvents, changes of `ReadyState` should be exposed to the client of this API using a channel: `chan<- ReadyState`.
The current ReadyState should stay private and be handled just by the goroutine who does HTTP connections.

**Comment by dolmen** [comment]
The channel could be a bit more verbose to also expose `error`s: `chan<- *Status`

``` go
type Status struct {
    ReadyState ReadyState
    Err error
}
func (s *Status) Error() string {
    return s.Err.Error()
}
```

**Comment by alevinval** [comment]
Reading the spec:

> When a user agent is to announce the connection, the user agent must queue a task which, if the readyState attribute is set to a value other than CLOSED, sets the readyState attribute to OPEN and fires an event named open at the EventSource object.

1) We should create a channel to get notifications of when connections get opened.

> When a user agent is to reestablish the connection
> If the readyState attribute is set to CLOSED, abort the task.
> Set the readyState attribute to CONNECTING.
> Fire an event named error at the EventSource object.

2) We should create a channel to get notifications of errors.

And looking at the eventsource interface:

>  // networking
>   attribute EventHandler onopen;
>   attribute EventHandler onmessage;
>   attribute EventHandler onerror;

Based on that, we have:
- [x] Channel for event messages.
- [ ] Channel for notifications of connection succeeding.
- [ ] Channel for notifications of errors.

---

If I understand, you propose to notify ReadyState changes, but the spec says we should notify Open events and Error events.
- I agree with extracting the logic for readyState and errors into `Status` (the mutex, the acquireClosingRight, ... )
- I think `Status` should not be exposed, should be `status` instead.
- I think `ReadyState` should be kept as a getter and no need to notify changes on it.

If you want to implement the `status` type and keep all handling of readyState and errors there, that would pave the road to implement the notification channels for `open` and `error` events.

What do you think?

**Comment by dolmen** [comment]
The spec is for JavaScript in browsers. This may not fit an idiomatic way to expose the similar functionality in Go. So don't look too strictly at how error handling is specified because error handling in Go is different.

My point in grouping ReadyState with errors is that some changes of ReadyState often occurs because of an error and the error usually provides more detailled information than the ReadyState.

`Status` must be public for the same reason as `Event`: once we send the `Status` through the channel the receiver (which is a client of our API) it is not anymore in our hands and the receiver can do anything with it, that will not affect us. So the cost of hidding with methods or an interface is not needed.

My vision of using channels for EventSource is that they would boundaries of the API: we send events and the client of the API is a receiver of a channel. We must expose channels directly. Not expose methods that wrap channels.

The point of using channels is to not use mutexes (explicitely). The client of the API would directly consume a channel of Status. Both connection success and errors would be reported with Status.
As I initially wrote, we don't have to maintain a copy of the latest ReadyState. If the client of the API needs to keep that ReadyState (which I doubt) it can implement it on his side around his select loop. Channels are helping to implement algorithms in a different way than what EventSource designers envisionned for the JS world.

**Comment by alevinval** [comment]
You are right. As long as we provide the building blocks, it will be okay. There is no need to follow so strictly the "implementation" from browser/javascript world into the golang world.

**Comment by alevinval** [comment]
Done in https://github.com/go-rfc/sse/pull/47
