### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by tiansin** [alevinval/sse#56]
https://github.com/alevinval/sse/blob/2e0e8d7146c1ec08cd5e13a264ca2bd7a92553dd/pkg/eventsource/eventsource.go#L177

**Comment by alevinval** [comment]
Thanks for raising the issue. I will take some time to think how can `eventsource.go` be written so that it does not have data races. Spawning the `consume` routine is kinda problematic as it is written now.

**Comment by alevinval** [comment]
The issue should be fixed now.
