### ISSUE TITLE
Listening for custom events (aka named messages)

### ISSUE THREAD

**Issue by g41797** [alevinval/sse#59]
According to https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events
for retrieving of **_named messages_** client should call addEventListener
It isn't clear (at least for me) whether **_onmessage_** handler will be called for named messages
As far as I understand your EventSource supports retrieving of all messages (named&unnamed) and doesn't implement EventSource interface
Please confirm

**Comment by alevinval** [comment]
[The message gives you the name of the event](https://github.com/alevinval/sse/blob/master/pkg/base/message_event.go#L16), if there is no named event, it will be an empty string. This should allow you to handle however you want each kind of named message. This library focuses on decoding/encoding, and I feel listening to only "specific" named events is something that is better solved by the user of the library, you can easily discard whatever event does not interest you.

**Comment by g41797** [comment]
Thanks!
