### ISSUE TITLE
Installation of sse 

### ISSUE THREAD

**Issue by g41797** [alevinval/sse#61]
Hi
I'd like to use **_decoder_** in https://github.com/gavv/httpexpect/issues/246

Result of "go get github.com/alevinval/sse"
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'

_**go install github.com/alevinval/sse@latest**_:
go: downloading github.com/alevinval/sse v1.0.1
go: github.com/alevinval/sse@latest: module github.com/alevinval/sse@latest found (v1.0.1), but does not contain package github.com/alevinval/sse

**_go install github.com/alevinval/sse/pkg/decoder@latest_**:
package github.com/alevinval/sse/pkg/decoder is not a main package

What I did wrong?
Thanks

**Comment by alevinval** [comment]
I'm not sure where you are running those commands, are you sure you have `go mod init`? Examples of people using the library:
https://github.com/akuity/grpc-gateway-client/blob/38ca1b4b439cfcf3897ce4e1f932bed7804258d1/go.mod
https://github.com/akuity/grpc-gateway-client/blob/38ca1b4b439cfcf3897ce4e1f932bed7804258d1/pkg/grpc/gateway/request.go#L10
